// <auto-generated />
using HomeWork65.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeWork65.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeWork65.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Tokyo",
                            Name = "Japan",
                            OfficialName = "State of Japan",
                            Population = 126300000,
                            Region = "Asia",
                            SubRegion = "Eastern Asia"
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Brasília",
                            Name = "Brazil",
                            OfficialName = "Federative Republic of Brazil",
                            Population = 213000000,
                            Region = "South America",
                            SubRegion = "South America"
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Canberra",
                            Name = "Australia",
                            OfficialName = "Commonwealth of Australia",
                            Population = 25690000,
                            Region = "Oceania",
                            SubRegion = "Australia and New Zealand"
                        },
                        new
                        {
                            Id = 4,
                            Capital = "New Delhi",
                            Name = "India",
                            OfficialName = "Republic of India",
                            Population = 1380000000,
                            Region = "Asia",
                            SubRegion = "Southern Asia"
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Mexico City",
                            Name = "Mexico",
                            OfficialName = "United Mexican States",
                            Population = 128900000,
                            Region = "North America",
                            SubRegion = "Central America"
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Rome",
                            Name = "Italy",
                            OfficialName = "Italian Republic",
                            Population = 60000000,
                            Region = "Europe",
                            SubRegion = "Southern Europe"
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Cairo",
                            Name = "Egypt",
                            OfficialName = "Arab Republic of Egypt",
                            Population = 104000000,
                            Region = "Africa",
                            SubRegion = "Northern Africa"
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Seoul",
                            Name = "South Korea",
                            OfficialName = "Republic of Korea",
                            Population = 51700000,
                            Region = "Asia",
                            SubRegion = "Eastern Asia"
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Buenos Aires",
                            Name = "Argentina",
                            OfficialName = "Argentine Republic",
                            Population = 45380000,
                            Region = "South America",
                            SubRegion = "South America"
                        },
                        new
                        {
                            Id = 10,
                            Capital = "Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)",
                            Name = "South Africa",
                            OfficialName = "Republic of South Africa",
                            Population = 59300000,
                            Region = "Africa",
                            SubRegion = "Southern Africa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
